FROM archlinux:base-devel

RUN pacman -Syu --noconfirm && \
    pacman -S --needed --noconfirm \
      cmake extra-cmake-modules ninja pkgconf \
      qt6-base qt6-declarative qt6-multimedia qt6-svg qt6-wayland \
      kirigami kcoreaddons ki18n karchive breeze-icons && \
    pacman -Scc --noconfirm

RUN useradd -m builder && \
    echo 'builder ALL=(ALL) NOPASSWD: ALL' >/etc/sudoers.d/builder

WORKDIR /build
